<?php

// Flat icons
function restan_flaticons()
{
    return [

'flaticon-start-up' => 'flaticon-start-up',
'flaticon-startup' => 'flaticon-startup',
'flaticon-growth' => 'flaticon-growth',
'flaticon-startup-1' => 'flaticon-startup-1',
'flaticon-shuttle' => 'flaticon-shuttle',
'flaticon-rocket' => 'flaticon-rocket',
'flaticon-rocket-1' => 'flaticon-rocket-1',
'flaticon-company' => 'flaticon-company',
'flaticon-development' => 'flaticon-development',
'flaticon-startup-2' => 'flaticon-startup-2',
'flaticon-idea' => 'flaticon-idea',
'flaticon-entrepreneur' => 'flaticon-entrepreneur',
'flaticon-startup-3' => 'flaticon-startup-3',
'flaticon-solution' => 'flaticon-solution',
'flaticon-startup-4' => 'flaticon-startup-4',
'flaticon-idea-1' => 'flaticon-idea-1',
'flaticon-boost' => 'flaticon-boost',
'flaticon-startup-5' => 'flaticon-startup-5',
'flaticon-start-up-1' => 'flaticon-start-up-1',
'flaticon-idea-2' => 'flaticon-idea-2',
'flaticon-presentation' => 'flaticon-presentation',
'flaticon-startup-6' => 'flaticon-startup-6',
'flaticon-cloud' => 'flaticon-cloud',
'flaticon-start-up-2' => 'flaticon-start-up-2',
'flaticon-report' => 'flaticon-report',
'flaticon-hand' => 'flaticon-hand',
'flaticon-envelope' => 'flaticon-envelope',
'flaticon-graph' => 'flaticon-graph',
'flaticon-paper' => 'flaticon-paper',
'flaticon-project' => 'flaticon-project',
'flaticon-project-1' => 'flaticon-project-1',
'flaticon-briefing' => 'flaticon-briefing',
'flaticon-management' => 'flaticon-management',
'flaticon-management-1' => 'flaticon-management-1',
'flaticon-complete' => 'flaticon-complete',
'flaticon-projects' => 'flaticon-projects',
'flaticon-project-management' => 'flaticon-project-management',
'flaticon-concept' => 'flaticon-concept',
'flaticon-document' => 'flaticon-document',
'flaticon-team' => 'flaticon-team',
'flaticon-project-2' => 'flaticon-project-2',
'flaticon-project-plan' => 'flaticon-project-plan',
'flaticon-software' => 'flaticon-software',
'flaticon-layers' => 'flaticon-layers',
'flaticon-coding' => 'flaticon-coding',
'flaticon-software-engineer' => 'flaticon-software-engineer',
'flaticon-programmer' => 'flaticon-programmer',
'flaticon-hardware' => 'flaticon-hardware',
'flaticon-web-development' => 'flaticon-web-development',
'flaticon-cloud-service' => 'flaticon-cloud-service',
'flaticon-license' => 'flaticon-license',
'flaticon-computer' => 'flaticon-computer',
'flaticon-smartphone' => 'flaticon-smartphone',
'flaticon-cloud-data' => 'flaticon-cloud-data',
'flaticon-biometrics' => 'flaticon-biometrics',
'flaticon-cloud-1' => 'flaticon-cloud-1',
'flaticon-software-1' => 'flaticon-software-1',
'flaticon-database' => 'flaticon-database',
'flaticon-3d-printing-software' => 'flaticon-3d-printing-software',
'flaticon-cloud-2' => 'flaticon-cloud-2',
'flaticon-software-2' => 'flaticon-software-2',
'flaticon-software-development' => 'flaticon-software-development',
'flaticon-cloud-computing' => 'flaticon-cloud-computing',
'flaticon-cloud-computing-1' => 'flaticon-cloud-computing-1',
'flaticon-file' => 'flaticon-file',
'flaticon-upload' => 'flaticon-upload',
'flaticon-upload-1' => 'flaticon-upload-1',
'flaticon-submit' => 'flaticon-submit',
'flaticon-cloud-upload' => 'flaticon-cloud-upload',
'flaticon-resume' => 'flaticon-resume',
'flaticon-research' => 'flaticon-research',
'flaticon-risk' => 'flaticon-risk',
'flaticon-secure' => 'flaticon-secure',
'flaticon-bullhorn' => 'flaticon-bullhorn',
'flaticon-risk-1' => 'flaticon-risk-1',
'flaticon-manager' => 'flaticon-manager',
'flaticon-data-processing' => 'flaticon-data-processing',
'flaticon-collaboration' => 'flaticon-collaboration',
'flaticon-operational-risk' => 'flaticon-operational-risk',
'flaticon-collaboration-1' => 'flaticon-collaboration-1',
'flaticon-management-2' => 'flaticon-management-2',
'flaticon-money-management' => 'flaticon-money-management',
'flaticon-online-business' => 'flaticon-online-business',
'flaticon-project-management-1' => 'flaticon-project-management-1',
'flaticon-data-management' => 'flaticon-data-management',
'flaticon-product-management' => 'flaticon-product-management',
'flaticon-data-management-1' => 'flaticon-data-management-1',
'flaticon-planning' => 'flaticon-planning',
'flaticon-marketing-agent' => 'flaticon-marketing-agent',
'flaticon-testing' => 'flaticon-testing',
'flaticon-conversation' => 'flaticon-conversation',
'flaticon-simulation' => 'flaticon-simulation',
'flaticon-antivirus' => 'flaticon-antivirus',
'flaticon-marketing-strategy' => 'flaticon-marketing-strategy',
'flaticon-cyber-security' => 'flaticon-cyber-security',
'flaticon-3d-printing' => 'flaticon-3d-printing',
'flaticon-cds' => 'flaticon-cds',
'flaticon-support' => 'flaticon-support',
'flaticon-technical-support' => 'flaticon-technical-support',
'flaticon-support-1' => 'flaticon-support-1',
'flaticon-customer-service' => 'flaticon-customer-service',
'flaticon-customer-support' => 'flaticon-customer-support',
'flaticon-technical-support-1' => 'flaticon-technical-support-1',
'flaticon-online-support' => 'flaticon-online-support',
'flaticon-cloud-service-1' => 'flaticon-cloud-service-1',
'flaticon-customer-service-1' => 'flaticon-customer-service-1',
'flaticon-data-analysis' => 'flaticon-data-analysis',
'flaticon-analysis' => 'flaticon-analysis',
'flaticon-monitoring' => 'flaticon-monitoring',
'flaticon-report-1' => 'flaticon-report-1',
'flaticon-market-analysis' => 'flaticon-market-analysis',
'flaticon-qualitative-research' => 'flaticon-qualitative-research',
'flaticon-analysis-1' => 'flaticon-analysis-1',
'flaticon-analysis-2' => 'flaticon-analysis-2',
'flaticon-data-analysis-1' => 'flaticon-data-analysis-1',
'flaticon-dashboard' => 'flaticon-dashboard',
'flaticon-monitoring-1' => 'flaticon-monitoring-1',
'flaticon-startup-7' => 'flaticon-startup-7',
'flaticon-badge' => 'flaticon-badge',
'flaticon-high-quality' => 'flaticon-high-quality',
'flaticon-premium-quality' => 'flaticon-premium-quality',
'flaticon-award' => 'flaticon-award',
'flaticon-diamond' => 'flaticon-diamond',
'flaticon-diamond-2' => 'flaticon-diamond-2',
'flaticon-research-1' => 'flaticon-research-1',
'flaticon-web-analysis' => 'flaticon-web-analysis',
'flaticon-monitoring-2' => 'flaticon-monitoring-2',
'flaticon-shield' => 'flaticon-shield',
'flaticon-security' => 'flaticon-security',
'flaticon-secure-1' => 'flaticon-secure-1',
'flaticon-secure-payment' => 'flaticon-secure-payment',
'flaticon-update' => 'flaticon-update',
'flaticon-update-1' => 'flaticon-update-1',
'flaticon-synchronization' => 'flaticon-synchronization',
'flaticon-data-integration' => 'flaticon-data-integration',
'flaticon-update-2' => 'flaticon-update-2',
'flaticon-technology' => 'flaticon-technology',


    ];
}

function restan_include_flaticons()
{
    return array_keys(restan_flaticons());
}
